### PR TITLE
Re-adding "JsonRpc::Server JsonRpc::Client" dependencies at the application level

### PR DESCRIPTION
**Pull request by bobsummerwill**
Re-adding "JsonRpc::Server JsonRpc::Client" dependencies at the application level, to account for the removal of these as implicit dependencies in webthree-helpers.

### CODE REVIEW

**Comment by chriseth** [comment]
I think the correct way would be to add these dependencies to `Web3::web3jsonrpc`, because they should be introduced there.

**Comment by bobsummerwill** [comment]
You mean by tweaking the CMake rules, so that they both get added automatically if you depend on `Web3::web3jsonrpc`?    Sure - I can do that.    That way you're going to get both of them whether you need them or not.    So your comment about ethminer only needing client would be something which could not be fixed, but maybe that is OK?

**Comment by bobsummerwill** [comment]
@chriseth said:

ethminer only uses client, I'm not sure if there might still be a link-time dependency on server
eth_use should be transitive
and alethzero only indirectly depends on libjsonrpc, right?

@bobsummerwill said:

Right - so we would add these link-dependencies into a new rule in:
https://github.com/ethereum/webthree-helpers/blob/develop/cmake/UseEth.cmake
All I am pointing out is that doing that would mean we have to always link both whether or not they are required. But that's what we were doing anyway. At least we would now be doing that ONLY for the subset which actually use it.

**Comment by chriseth** [comment]
I think we might be able to remove them from here: https://github.com/ethereum/webthree-helpers/blob/develop/cmake/UseEth.cmake#L90

**Comment by bobsummerwill** [comment]
Yes.  That's the other half of the fix!   https://github.com/ethereum/webthree-helpers/pull/89/files
This change was a required "extra change" to keep the build working after that edit.
But I can improve it, as per your suggestion.
I'll keep iterating.

The downside to "auto-adding" here is that we need to auto-add both client and server libs, even if a particular application only uses part of `Web3::web3jsonprc', but that's not so terrible.

**Comment by bobsummerwill** [comment]
So this PR might be redundant, following an update I made to https://github.com/ethereum/webthree-helpers/pull/89.    If that works then I will close this PR, because we won't need it.

**Comment by bobsummerwill** [comment]
OK - I'll ditch this now.

**Pull request closed without merging**
