### PR TITLE
fix font size in withdraw dialog

### PR DESCRIPTION
**Pull request by winsvega**
make dialog size fixed

connects to #181

### CODE REVIEW

**Comment by chriseth** [comment]
@yann300 @LianaHus could you please take a look? It looks completely borked on my machine anyway....

**Comment by winsvega** [comment]
you mean the text or build?

**Comment by chriseth** [comment]
@LianaHus you had some comments here if I remember correctly.

**Comment by winsvega** [comment]
it was in another mix pr
https://github.com/ethereum/mix/pull/243

**Pull request merged**
