### PR TITLE
Size constraint fixes in dialogs.

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/webthree-umbrella/issues/178

### CODE REVIEW

**Comment by LianaHus** [comment]
rebase needed

**Comment by LianaHus** [comment]
isn't it too big? also send and cancel buttons are too wide for this dialog

**Comment by chriseth** [comment]
Can you make a screenshot?

**Comment by LianaHus** [comment]
screenshot from 2016-02-24 16 51 38

I would suggest maximumSize.width = 80

screenshot from 2016-02-24 16 58 05

And to be honest I would suggest to limit the address editbox size to the address size. @winsvega was working on that if I'm not mistaken

**Comment by LianaHus** [comment]
same with Reward Address, as you see it's too small so one should scroll it to check. If you want I can do a different pr for those fields

**Comment by LianaHus** [comment]
another problem is error check on value or address edit. I believe that should be done on Send clicked.

**Comment by chriseth** [comment]
Issues will be fixed in a subsequent PR.

**Pull request merged**
