### PR TITLE
WIP - Removed AlethFive application, which we are no longer supporting

### PR DESCRIPTION
**Pull request by bobsummerwill**
Removed AlethZero and AlethFive applications, which we are no longer supporting, to better manage our scope.

Fixes: https://github.com/ethereum/webthree-umbrella/issues/142

### CODE REVIEW

**Comment by chriseth** [comment]
Please explain why it helps managing scope.
To my knowledge, AlethZero does not pull in more dependencies than AlethOne.
I think the decision was to keep alethzero, but do not announce/recommend it or fix serious bugs in it. It is still useful until we have a 90% replacement for it.

**Comment by bobsummerwill** [comment]
One less application for everyone to build.    Quicker automation.   Less binaries to deliver in Homebrew, PPAs, zips.  One less application for end-users to get confused by wondering whether they want AlethZero or AlethOne or AlethFive, or eth, or flu, geth, or ...
Less bug reports.

It's a minor saving, but every little helps.    Probably reducing confusion in end-users is the most important reason for any of this "trimming".

**Comment by chriseth** [comment]
Please rebase to remove the removal of alethzero, I don't like my `git blame` to be messed up.

**Comment by bobsummerwill** [comment]
Content now correct.   Just need to squash, and also dig up other fixes in webthree-helpers, etc, and check they only remove AlethFive.

flu still TODO as well.   That will be a separate PR, because it's another repo.

**Comment by bobsummerwill** [comment]
Made a new one - https://github.com/ethereum/alethzero/pull/142.
Tried to rebase, but my git-foo is obviously still a little weak.

**Pull request closed without merging**
